name: "opa"
# Version is the version of Helm plus the number of official builds for this
# plugin
version: "2.5.1+2"
usage: "opa <path to chart>"
description: "Checks rendered charts against OPA policies"
command: "$HELM_PLUGIN_DIR/helm-opa"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"

useTunnel: false
ignoreFlags: false
